name: example
description: Example demonstrating BDK Dart usage.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.1

dependencies:
  bdk_dart:
    path: ../

dev_dependencies:
  lints: ^6.0.0
