name: bdk_dart
description: Dart bindings for bdk-ffi
version: 2.3.0-alpha.0

environment:
  sdk: "^3.10.0"

dependencies:
  ffi: ^2.1.4
  hooks: ^1.0.0
  code_assets: ^1.0.0
  native_toolchain_rs: ^1.0.0
dev_dependencies:
  test: ^1.26.2
  http: ^1.4.0

hooks:
  build: hook/build.dart
